### ISSUE TITLE
Enhance get node content REST API 

### ISSUE THREAD

**Issue by topce** [Alfresco/alfresco-community-repo#2668]
Enhance get node content REST API (/nodes/{nodeId}/content) to return content if node has property that has type content.
Currently REST API return error if type is not match ContentModel.TYPE_CONTENT and not consider if 
node has property of type Content.

**Comment by aborroy** [comment]
A follow-up JIRA ticket has been created: https://hyland.atlassian.net/browse/MNT-24468

**Comment by HeinRagas** [comment]
This all depends on what is meant with "the content of a node". This patch implies that "the content of a node" is either the content attached to a node or the first property with the type 'Content' that is found.
What if there is a second property with the type 'Content'? Does nodeService.getProperties return the list of properties always in the same order? Because if not, then the behavior won't be consistent because you can not predict _which_ content property you are going to get.
The property type "content" is also not mentioned in the list of possible property data types in our documentation.

**Comment by topce** [comment]
@HeinRagas it is good question: what to do if there is more then one property with property type  d:content?
In my case (my model) it is just one property, but indeed it could be more.
I could change code if there is multiple properties to sort properties by qname ascending and return first one.
Other solution is to change REST API add optional parameter for example in query: 
what content property we want to download in case there are multiple of them.

**Comment by topce** [comment]
Yet another option is to change existing API to return content if there is exactly  one d:content property 
and if there are more then one we throw exception because we do not know what property user want to download!
Currently if node type is content and node property is content  it return content otherwise it does not,
even node can also have content it does not return it

**Comment by HeinRagas** [comment]
I think I see two options:
- Extend the existing /nodes/{nodeId}/content API with an optional property parameter. If not set, you get the behavior as it is now. If it is set, and the property is of type d:content, you get the content of the property. Otherwise you get an error message.
- Create a new /nodes/{nodeId}/content/{property} endpoint which acts the same as described above.

**Comment by topce** [comment]
@aborroy  and @HeinRagas  
Thank you both for your time!
As you will implement  new feature I will close this PR
